// SPDX-License-Identifier: GPL-2.0
/*
 * glue/helper.sh.c - contents of diagfs/helper.sh as a C string.
 *
 * This file is generated from the canonical shell script; see the top of
 * the embedded script itself (below) for what it does and how to use it.
 * It is served read-only (mode 0555) at the root of the lkm4ctr diagfs
 * mount by lkm4ctr_diagfs.c (see LKM4CTR_DIAG_HELPER_SCRIPT).
 */
#include <linux/types.h>

const char lkm4ctr_helper_sh_data[] =
"#!/bin/sh\n"
"# SPDX-License-Identifier: GPL-2.0\n"
"#\n"
"# lkm4ctr diagfs helper functions (flattened layout).\n"
"#\n"
"# Usage:\n"
"#   export lkm4ctr_diagfs=/path/to/mountpoint\n"
"#   . \"$lkm4ctr_diagfs/helper.sh\"\n"
"#   lkm4ctr status\n"
"#   lkm4ctr off                 # graceful self-unload (writes to /status)\n"
"#   lkm4ctr forceunload\n"
"#   lkm4ctr v                   # list the /v resource tree\n"
"#   lkm4ctr resources           # list reference holders blocking rmmod\n"
"#   lkm4ctr logcat\n"
"#   lkm4ctr hot-upgrade /path/to/new/lkm4ctr.ko\n"
"#\n"
"# The diagfs root is exactly: /status /log /v/ /helper.sh /readme.txt /resources.\n"
"# This file is served read-only (0555) directly from the \"lkm4ctr\" diagfs\n"
"# mount root by lkm4ctr_diagfs.c; its contents live as a plain C string in\n"
"# glue/helper.sh.c. It is meant to be sourced (\". helper.sh\"), not\n"
"# executed directly, though the shebang line above makes `sh helper.sh`\n"
"# (with no arguments) harmless: it just prints usage and exits.\n"
"\n"
"_lkm4ctr_check_mnt() {\n"
"	if [ -z \"$lkm4ctr_diagfs\" ]; then\n"
"		echo \"lkm4ctr: \\$lkm4ctr_diagfs is not set; run: export lkm4ctr_diagfs=/path/to/mountpoint\" >&2\n"
"		return 1\n"
"	fi\n"
"	return 0\n"
"}\n"
"\n"
"_lkm4ctr_check_mounted() {\n"
"	_lkm4ctr_check_mnt || return 1\n"
"	if [ ! -e \"$lkm4ctr_diagfs/status\" ]; then\n"
"		echo \"lkm4ctr: \\\"$lkm4ctr_diagfs\\\" does not look like a mounted lkm4ctr diagfs (no /status); try: lkm4ctr mount\" >&2\n"
"		return 1\n"
"	fi\n"
"	return 0\n"
"}\n"
"\n"
"lkm4ctr_mount() {\n"
"	_lkm4ctr_check_mnt || return 1\n"
"	if [ -e \"$lkm4ctr_diagfs/status\" ]; then\n"
"		echo \"lkm4ctr: already mounted at \\\"$lkm4ctr_diagfs\\\"\"\n"
"		return 0\n"
"	fi\n"
"	mkdir -p \"$lkm4ctr_diagfs\" 2>/dev/null\n"
"	mount -t lkm4ctr diag \"$lkm4ctr_diagfs\" && \\\n"
"		echo \"lkm4ctr: mounted at \\\"$lkm4ctr_diagfs\\\"\"\n"
"}\n"
"\n"
"lkm4ctr_umount() {\n"
"	_lkm4ctr_check_mnt || return 1\n"
"	umount \"$lkm4ctr_diagfs\" 2>/dev/null || umount -l \"$lkm4ctr_diagfs\"\n"
"}\n"
"\n"
"lkm4ctr_status() {\n"
"	_lkm4ctr_check_mounted || return 1\n"
"	echo \"== status ==\"\n"
"	cat \"$lkm4ctr_diagfs/status\"\n"
"	echo \"== resources (holders blocking rmmod) ==\"\n"
"	ls -1 \"$lkm4ctr_diagfs/resources\" 2>/dev/null\n"
"	echo \"== v/references ==\"\n"
"	cat \"$lkm4ctr_diagfs/v/references\" 2>/dev/null\n"
"	echo \"== v/hotreload/status ==\"\n"
"	cat \"$lkm4ctr_diagfs/v/hotreload/status\" 2>/dev/null\n"
"	if [ -e \"$lkm4ctr_diagfs/v/status\" ]; then\n"
"		printf 'v: '\n"
"		cat \"$lkm4ctr_diagfs/v/status\"\n"
"	fi\n"
"}\n"
"\n"
"# The module-wide command surface is the single rw /status file.\n"
"lkm4ctr_on() {\n"
"	_lkm4ctr_check_mounted || return 1\n"
"	echo on > \"$lkm4ctr_diagfs/status\"\n"
"}\n"
"lkm4ctr_off() {\n"
"	_lkm4ctr_check_mounted || return 1\n"
"	echo off > \"$lkm4ctr_diagfs/status\"\n"
"}\n"
"lkm4ctr_forceunload() {\n"
"	_lkm4ctr_check_mounted || return 1\n"
"	echo forceunload > \"$lkm4ctr_diagfs/status\"\n"
"}\n"
"lkm4ctr_force2() {\n"
"	_lkm4ctr_check_mounted || return 1\n"
"	echo force2 > \"$lkm4ctr_diagfs/status\"\n"
"}\n"
"\n"
"# lkm4ctr_control <target> <command>\n"
"#   target: status (module-wide, the default) or v (the vendor_kernel subsystem)\n"
"#   command: load, unload, forceunload; force2 is module-wide (status) only.\n"
"lkm4ctr_control() {\n"
"	_lkm4ctr_check_mounted || return 1\n"
"	target=\"$1\"\n"
"	cmd=\"$2\"\n"
"	if [ -z \"$cmd\" ]; then\n"
"		echo \"usage: lkm4ctr control <status|v> <load|unload|forceunload|force2>\" >&2\n"
"		return 1\n"
"	fi\n"
"	case \"$target\" in\n"
"	v|vendor_kernel)\n"
"		echo \"$cmd\" > \"$lkm4ctr_diagfs/v/control\" ;;\n"
"	status|global|\"\")\n"
"		echo \"$cmd\" > \"$lkm4ctr_diagfs/status\" ;;\n"
"	*)\n"
"		echo \"lkm4ctr: no such control target \\\"$target\\\" (use status or v)\" >&2\n"
"		return 1 ;;\n"
"	esac\n"
"}\n"
"\n"
"# load/unload default to the module-wide /status surface; pass \"v\" to act on\n"
"# just the vendor_kernel subsystem via /v/control.\n"
"lkm4ctr_load() {\n"
"	if [ -n \"$1\" ]; then lkm4ctr_control \"$1\" load; else lkm4ctr_on; fi\n"
"}\n"
"lkm4ctr_unload() {\n"
"	if [ -n \"$1\" ]; then lkm4ctr_control \"$1\" unload; else lkm4ctr_off; fi\n"
"}\n"
"\n"
"# lkm4ctr_logcat [target]\n"
"#   target defaults to \"\" (the flattened, unfiltered global /log); pass\n"
"#   \"v\" for vendor_kernel's own log, or \"hotreload\" for the hot-reload log.\n"
"lkm4ctr_logcat() {\n"
"	_lkm4ctr_check_mounted || return 1\n"
"	target=\"${1:-}\"\n"
"	if [ \"$target\" = \"hotreload\" ]; then\n"
"		cat \"$lkm4ctr_diagfs/v/hotreload/log\"\n"
"		return\n"
"	fi\n"
"	if [ -z \"$target\" ]; then\n"
"		cat \"$lkm4ctr_diagfs/log\"\n"
"		return\n"
"	fi\n"
"	if [ ! -e \"$lkm4ctr_diagfs/$target/log\" ]; then\n"
"		echo \"lkm4ctr: no such log \\\"$target\\\"\" >&2\n"
"		return 1\n"
"	fi\n"
"	cat \"$lkm4ctr_diagfs/$target/log\"\n"
"}\n"
"\n"
"# lkm4ctr_references - who is holding a module reference right now.\n"
"lkm4ctr_references() {\n"
"	_lkm4ctr_check_mounted || return 1\n"
"	cat \"$lkm4ctr_diagfs/v/references\"\n"
"}\n"
"\n"
"# lkm4ctr_resources [name [rm]] - list, inspect, or delete rmmod-blocking\n"
"# reference holders under /resources.\n"
"#   lkm4ctr resources            list every holder (one file per holder)\n"
"#   lkm4ctr resources <name>     cat detail about that holder\n"
"#   lkm4ctr resources <name> rm  delete (forcibly clear) that holder\n"
"lkm4ctr_resources() {\n"
"	_lkm4ctr_check_mounted || return 1\n"
"	name=\"$1\"\n"
"	if [ -z \"$name\" ]; then\n"
"		ls -1 \"$lkm4ctr_diagfs/resources\" 2>/dev/null\n"
"		return\n"
"	fi\n"
"	if [ \"$2\" = \"rm\" ] || [ \"$2\" = \"delete\" ]; then\n"
"		rm \"$lkm4ctr_diagfs/resources/$name\"\n"
"		return\n"
"	fi\n"
"	cat \"$lkm4ctr_diagfs/resources/$name\"\n"
"}\n"
"\n"
"# lkm4ctr_v [subpath] - list the /v live-resource tree, or cat a path under it.\n"
"lkm4ctr_v() {\n"
"	_lkm4ctr_check_mounted || return 1\n"
"	if [ -n \"$1\" ]; then\n"
"		if [ -d \"$lkm4ctr_diagfs/v/$1\" ]; then\n"
"			ls -1 \"$lkm4ctr_diagfs/v/$1\"\n"
"		else\n"
"			cat \"$lkm4ctr_diagfs/v/$1\"\n"
"		fi\n"
"		return\n"
"	fi\n"
"	if command -v find >/dev/null 2>&1; then\n"
"		find \"$lkm4ctr_diagfs/v\" 2>/dev/null\n"
"	else\n"
"		ls -1 \"$lkm4ctr_diagfs/v\"\n"
"	fi\n"
"}\n"
"\n"
"# lkm4ctr_hot_upgrade /path/to/new/lkm4ctr.ko\n"
"lkm4ctr_hot_upgrade() {\n"
"	_lkm4ctr_check_mounted || return 1\n"
"	if [ -z \"$1\" ]; then\n"
"		echo \"usage: lkm4ctr hot-upgrade /path/to/new/lkm4ctr.ko\" >&2\n"
"		return 1\n"
"	fi\n"
"	echo \"$1\" > \"$lkm4ctr_diagfs/v/hotreload/do-hot-reload\"\n"
"}\n"
"\n"
"lkm4ctr_help() {\n"
"	cat <<'EOF'\n"
"lkm4ctr <command> [args...]\n"
"  mount                          mount -t lkm4ctr diag \"$lkm4ctr_diagfs\"\n"
"  umount                         unmount \"$lkm4ctr_diagfs\"\n"
"  status                         summarise /status + /resources + /v state\n"
"  on                             echo on > /status (load every submodule)\n"
"  off                            echo off > /status (graceful self-unload)\n"
"  forceunload                    echo forceunload > /status\n"
"  force2                         echo force2 > /status (aggressive escalation)\n"
"  control <target> <cmd>         write <cmd> to /status (target status) or /v/control (target v)\n"
"  load [target]                  on, or control <target> load\n"
"  unload [target]                off, or control <target> unload\n"
"  logcat [target]                cat /log (default), /v/log (target \"v\"), or /v/hotreload/log (\"hotreload\")\n"
"  references                     cat /v/references\n"
"  resources [name [rm]]          list / cat / delete rmmod-blocking holders under /resources\n"
"  v [subpath]                    list the /v live-resource tree, or cat a path under it\n"
"  hot-upgrade <path-to-ko>       echo <path> > /v/hotreload/do-hot-reload\n"
"  help                           this text\n"
"\n"
"$lkm4ctr_diagfs must be exported to the lkm4ctr diagfs mountpoint first.\n"
"SAFE-RMMOD: when `lkm4ctr resources` lists only the mount you are reading\n"
"through, it is safe to `lkm4ctr umount` and then `rmmod lkm4ctr`.\n"
"EOF\n"
"}\n"
"\n"
"# lkm4ctr <mount|umount|status|on|off|control|load|unload|forceunload|force2|logcat|references|resources|v|hot-upgrade|help> [args...]\n"
"lkm4ctr() {\n"
"	cmd=\"$1\"\n"
"	[ $# -gt 0 ] && shift\n"
"	case \"$cmd\" in\n"
"	mount) lkm4ctr_mount \"$@\" ;;\n"
"	umount) lkm4ctr_umount \"$@\" ;;\n"
"	status) lkm4ctr_status \"$@\" ;;\n"
"	on) lkm4ctr_on \"$@\" ;;\n"
"	off) lkm4ctr_off \"$@\" ;;\n"
"	control) lkm4ctr_control \"$@\" ;;\n"
"	load) lkm4ctr_load \"$@\" ;;\n"
"	unload) lkm4ctr_unload \"$@\" ;;\n"
"	forceunload) lkm4ctr_forceunload \"$@\" ;;\n"
"	force2) lkm4ctr_force2 \"$@\" ;;\n"
"	logcat) lkm4ctr_logcat \"$@\" ;;\n"
"	references) lkm4ctr_references \"$@\" ;;\n"
"	resources) lkm4ctr_resources \"$@\" ;;\n"
"	v) lkm4ctr_v \"$@\" ;;\n"
"	hot-upgrade|hot_upgrade|hotupgrade) lkm4ctr_hot_upgrade \"$@\" ;;\n"
"	help|\"\"|*) lkm4ctr_help ;;\n"
"	esac\n"
"}\n"
"\n"
"if [ \"${0##*/}\" = \"helper.sh\" ]; then\n"
"	lkm4ctr_help\n"
"fi\n";

const unsigned long lkm4ctr_helper_sh_size = sizeof(lkm4ctr_helper_sh_data) - 1;
