// SPDX-License-Identifier: GPL-2.0
/*
 * glue/helper.sh.c - contents of diagfs/helper.sh as a C string.
 *
 * This file is generated from the canonical shell script; see the top of
 * the embedded script itself (below) for what it does and how to use it.
 * It is served read-only (mode 0555) at the root of the lkm4ctr diagfs
 * mount by lkm4ctr_diagfs.c (see LKM4CTR_DIAG_HELPER_SCRIPT).
 */
#include <linux/types.h>

const char lkm4ctr_helper_sh_data[] =
"#!/bin/sh\n"
"# SPDX-License-Identifier: GPL-2.0\n"
"#\n"
"# lkm4ctr diagfs helper functions.\n"
"#\n"
"# Usage:\n"
"#   export lkm4ctr_diagfs=/path/to/mountpoint\n"
"#   . \"$lkm4ctr_diagfs/helper.sh\"\n"
"#   lkm4ctr status\n"
"#   lkm4ctr control vendor_kernel unload\n"
"#   lkm4ctr control global forceunload\n"
"#   lkm4ctr logcat vendor_kernel\n"
"#   lkm4ctr hot-upgrade /path/to/new/lkm4ctr.ko\n"
"#\n"
"# This file is served read-only (0555) directly from the \"lkm4ctr\" diagfs\n"
"# mount root by lkm4ctr_diagfs.c; its contents live as a plain C string in\n"
"# glue/helper.sh.c. It is meant to be sourced (\". helper.sh\"), not\n"
"# executed directly, though the shebang line above makes `sh helper.sh`\n"
"# (with no arguments) harmless: it just prints usage and exits.\n"
"\n"
"_lkm4ctr_check_mnt() {\n"
"	if [ -z \"$lkm4ctr_diagfs\" ]; then\n"
"		echo \"lkm4ctr: \\$lkm4ctr_diagfs is not set; run: export lkm4ctr_diagfs=/path/to/mountpoint\" >&2\n"
"		return 1\n"
"	fi\n"
"	return 0\n"
"}\n"
"\n"
"_lkm4ctr_check_mounted() {\n"
"	_lkm4ctr_check_mnt || return 1\n"
"	if [ ! -e \"$lkm4ctr_diagfs/global/control\" ]; then\n"
"		echo \"lkm4ctr: \\\"$lkm4ctr_diagfs\\\" does not look like a mounted lkm4ctr diagfs (no global/control); try: lkm4ctr mount\" >&2\n"
"		return 1\n"
"	fi\n"
"	return 0\n"
"}\n"
"\n"
"lkm4ctr_mount() {\n"
"	_lkm4ctr_check_mnt || return 1\n"
"	if [ -e \"$lkm4ctr_diagfs/global/control\" ]; then\n"
"		echo \"lkm4ctr: already mounted at \\\"$lkm4ctr_diagfs\\\"\"\n"
"		return 0\n"
"	fi\n"
"	mkdir -p \"$lkm4ctr_diagfs\" 2>/dev/null\n"
"	mount -t lkm4ctr diag \"$lkm4ctr_diagfs\" && \\\n"
"		echo \"lkm4ctr: mounted at \\\"$lkm4ctr_diagfs\\\"\"\n"
"}\n"
"\n"
"lkm4ctr_umount() {\n"
"	_lkm4ctr_check_mnt || return 1\n"
"	umount \"$lkm4ctr_diagfs\" 2>/dev/null || umount -l \"$lkm4ctr_diagfs\"\n"
"}\n"
"\n"
"lkm4ctr_status() {\n"
"	_lkm4ctr_check_mounted || return 1\n"
"	echo \"== global/status ==\"\n"
"	cat \"$lkm4ctr_diagfs/global/status\"\n"
"	echo \"== global/references ==\"\n"
"	cat \"$lkm4ctr_diagfs/global/references\"\n"
"	echo \"== hotreload/status ==\"\n"
"	cat \"$lkm4ctr_diagfs/global/hotreload/status\"\n"
"	for m in vendor_kernel; do\n"
"		if [ -e \"$lkm4ctr_diagfs/$m/status\" ]; then\n"
"			printf '%s: ' \"$m\"\n"
"			cat \"$lkm4ctr_diagfs/$m/status\"\n"
"		fi\n"
"	done\n"
"}\n"
"\n"
"# lkm4ctr_control <target> <command>\n"
"#   target: global, vendor_kernel\n"
"#   command: load, unload, forceunload, force2 (global only), 1/remove/graceful/force/force_unload\n"
"lkm4ctr_control() {\n"
"	_lkm4ctr_check_mounted || return 1\n"
"	target=\"$1\"\n"
"	cmd=\"$2\"\n"
"	if [ -z \"$target\" ] || [ -z \"$cmd\" ]; then\n"
"		echo \"usage: lkm4ctr control <global|vendor_kernel> <load|unload|forceunload|force2>\" >&2\n"
"		return 1\n"
"	fi\n"
"	if [ ! -e \"$lkm4ctr_diagfs/$target/control\" ]; then\n"
"		echo \"lkm4ctr: no such target \\\"$target\\\" (no $lkm4ctr_diagfs/$target/control)\" >&2\n"
"		return 1\n"
"	fi\n"
"	echo \"$cmd\" > \"$lkm4ctr_diagfs/$target/control\"\n"
"}\n"
"\n"
"lkm4ctr_load() { lkm4ctr_control \"${1:-global}\" load; }\n"
"lkm4ctr_unload() { lkm4ctr_control \"${1:-global}\" unload; }\n"
"lkm4ctr_forceunload() { lkm4ctr_control \"${1:-global}\" forceunload; }\n"
"lkm4ctr_force2() { lkm4ctr_control global force2; }\n"
"\n"
"# lkm4ctr_logcat [target]\n"
"#   target defaults to \"global\"; pass a submodule name (vendor_kernel)\n"
"#   or \"hotreload\" for the hot-reload log.\n"
"lkm4ctr_logcat() {\n"
"	_lkm4ctr_check_mounted || return 1\n"
"	target=\"${1:-global}\"\n"
"	if [ \"$target\" = \"hotreload\" ]; then\n"
"		cat \"$lkm4ctr_diagfs/global/hotreload/log\"\n"
"		return\n"
"	fi\n"
"	if [ ! -e \"$lkm4ctr_diagfs/$target/log\" ]; then\n"
"		echo \"lkm4ctr: no such log \\\"$target\\\"\" >&2\n"
"		return 1\n"
"	fi\n"
"	cat \"$lkm4ctr_diagfs/$target/log\"\n"
"}\n"
"\n"
"# lkm4ctr_references [target]\n"
"lkm4ctr_references() {\n"
"	_lkm4ctr_check_mounted || return 1\n"
"	target=\"${1:-global}\"\n"
"	cat \"$lkm4ctr_diagfs/$target/references\"\n"
"}\n"
"\n"
"# lkm4ctr_hot_upgrade /path/to/new/lkm4ctr.ko\n"
"lkm4ctr_hot_upgrade() {\n"
"	_lkm4ctr_check_mounted || return 1\n"
"	if [ -z \"$1\" ]; then\n"
"		echo \"usage: lkm4ctr hot-upgrade /path/to/new/lkm4ctr.ko\" >&2\n"
"		return 1\n"
"	fi\n"
"	echo \"$1\" > \"$lkm4ctr_diagfs/global/hotreload/do-hot-reload\"\n"
"}\n"
"\n"
"lkm4ctr_help() {\n"
"	cat <<'EOF'\n"
"lkm4ctr <command> [args...]\n"
"  mount                          mount -t lkm4ctr diag \"$lkm4ctr_diagfs\"\n"
"  umount                         unmount \"$lkm4ctr_diagfs\"\n"
"  status                         summarise global + every submodule's status\n"
"  control <target> <cmd>         write <cmd> to <target>/control\n"
"  load [target]                  control <target|global> load\n"
"  unload [target]                control <target|global> unload\n"
"  forceunload [target]           control <target|global> forceunload\n"
"  force2                         control global force2 (aggressive escalation)\n"
"  logcat [target]                cat <target|global>/log (\"hotreload\" for the hot-reload log)\n"
"  references [target]            cat <target|global>/references\n"
"  hot-upgrade <path-to-ko>       echo <path> > global/hotreload/do-hot-reload\n"
"  help                           this text\n"
"\n"
"$lkm4ctr_diagfs must be exported to the lkm4ctr diagfs mountpoint first.\n"
"EOF\n"
"}\n"
"\n"
"# lkm4ctr <mount|umount|status|control|load|unload|forceunload|force2|logcat|references|hot-upgrade|help> [args...]\n"
"lkm4ctr() {\n"
"	cmd=\"$1\"\n"
"	[ $# -gt 0 ] && shift\n"
"	case \"$cmd\" in\n"
"	mount) lkm4ctr_mount \"$@\" ;;\n"
"	umount) lkm4ctr_umount \"$@\" ;;\n"
"	status) lkm4ctr_status \"$@\" ;;\n"
"	control) lkm4ctr_control \"$@\" ;;\n"
"	load) lkm4ctr_load \"$@\" ;;\n"
"	unload) lkm4ctr_unload \"$@\" ;;\n"
"	forceunload) lkm4ctr_forceunload \"$@\" ;;\n"
"	force2) lkm4ctr_force2 \"$@\" ;;\n"
"	logcat) lkm4ctr_logcat \"$@\" ;;\n"
"	references) lkm4ctr_references \"$@\" ;;\n"
"	hot-upgrade|hot_upgrade|hotupgrade) lkm4ctr_hot_upgrade \"$@\" ;;\n"
"	help|\"\"|*) lkm4ctr_help ;;\n"
"	esac\n"
"}\n"
"\n"
"if [ \"${0##*/}\" = \"helper.sh\" ]; then\n"
"	lkm4ctr_help\n"
"fi\n";

const unsigned long lkm4ctr_helper_sh_size = sizeof(lkm4ctr_helper_sh_data) - 1;
