// SPDX-License-Identifier: GPL-2.0
/*
 * glue/readme.txt.c - contents of diagfs/readme.txt as a C string.
 *
 * This mirrors helper.sh.c: the canonical text lives here as a plain C
 * string and is served read-only (mode 0444) at the root of the lkm4ctr
 * diagfs mount by lkm4ctr_diagfs.c (see LKM4CTR_DIAG_README). It exists so
 * that anyone who mounts the filesystem, without any prior documentation,
 * can `cat readme.txt` and learn the full tree layout and how to drive it,
 * without needing this repository's source tree at all.
 */
#include <linux/types.h>

const char lkm4ctr_readme_txt_data[] =
"lkm4ctr diagfs - readme\n"
"========================\n"
"\n"
"This is the \"lkm4ctr\" pseudo-filesystem exposed by the lkm4ctr.ko kernel\n"
"module. Mounting it gives you a read/write diagnostics and control tree\n"
"covering vendor_kernel (the only runtime-loadable subsystem linked into\n"
"lkm4ctr.ko; the shared ftrace/kprobe hook engine and the former\n"
"shadow_cgdevices submodule are no longer separately loadable), plus\n"
"module-wide load/unload/hot-reload control.\n"
"\n"
"This file is generated from the canonical diagfs documentation living in\n"
"glue/readme.txt.c, and is kept in sync with lkm4ctr_diagfs.c by hand.\n"
"\n"
"Quick start\n"
"-----------\n"
"  # insert the module; vendor_kernel auto-loads at insmod time\n"
"  insmod lkm4ctr.ko\n"
"\n"
"  # mount the filesystem somewhere (any empty directory)\n"
"  mkdir -p /mnt/lkm4ctr\n"
"  mount -t lkm4ctr diag /mnt/lkm4ctr\n"
"\n"
"  # inspect overall state\n"
"  cat /mnt/lkm4ctr/status\n"
"  cat /mnt/lkm4ctr/log\n"
"  cat /mnt/lkm4ctr/v/status\n"
"  cat /mnt/lkm4ctr/v/log\n"
"\n"
"  # or source the bundled shell helper for a friendlier interface\n"
"  export lkm4ctr_diagfs=/mnt/lkm4ctr\n"
"  . \"$lkm4ctr_diagfs/helper.sh\"\n"
"  lkm4ctr status\n"
"  lkm4ctr help\n"
"\n"
"See \"helper.sh\" below for the full command reference of that wrapper; it\n"
"is entirely optional -- every diagfs file can just as well be read with\n"
"cat/echo directly, which is what the wrapper itself does under the hood.\n"
"\n"
"The root is flat: exactly /status, /log, /v/, /helper.sh, /readme.txt and\n"
"/resources. /status is read/write (read: lifecycle state; write: the\n"
"module-wide command surface). Every \"status\"/\"log\"/listing file is\n"
"regenerated fresh on every open(), so repeated `cat`s always show live\n"
"state.\n"
"\n"
"Root layout\n"
"-----------\n"
"  ./status                       (0644) read/write. READ: the whole\n"
"                                   module's lifecycle state, one of\n"
"                                   \"active\" / \"inactive\" / \"unloading\"\n"
"                                   (plus the transient \"loading\"). WRITE:\n"
"                                   the merged command surface --\n"
"    on                            (alias: load) load every diagfs-managed\n"
"                                   submodule\n"
"    off                           (aliases: unload, 1, remove, graceful)\n"
"                                   graceful whole-module self-unload\n"
"    forceunload                   (aliases: force, force_unload) force\n"
"                                   whole-module self-unload\n"
"    force2                        start (or escalate an in-progress unload\n"
"                                   to) the aggressive force2 sequence, which\n"
"                                   overrides module_refcount() bookkeeping\n"
"                                   directly to push an unload through even\n"
"                                   when references look stuck.\n"
"  ./log                          (0444, read-only) the flattened,\n"
"                                   unfiltered global log: every log line\n"
"                                   from every subsystem, tag-unfiltered.\n"
"                                   ./v/log and ./v/hotreload/log remain as\n"
"                                   tag-filtered views of the same\n"
"                                   underlying ring buffer.\n"
"  ./helper.sh                    (0555, read+execute) POSIX-sh helper\n"
"                                   script; see \"Shell helper\" below.\n"
"  ./readme.txt                   (0444, read-only) this file.\n"
"  ./resources/                   a directory with one file per real\n"
"                                   reference currently blocking a safe\n"
"                                   `rmmod`:\n"
"    mount-<n>                     each active lkm4ctr diagfs mount\n"
"    hook-<n>                      each in-flight shadow_hook-redirected call\n"
"    other-<n>                     each still-unaccounted external reference\n"
"                                   `cat`ing one describes that specific\n"
"                                   holder; deleting one (rm) forcibly clears\n"
"                                   it where possible -- mount and hook\n"
"                                   deletions are honestly *aggregate* (they\n"
"                                   umount all lkm4ctr mounts / drain all\n"
"                                   in-flight hooks), \"other\" holders cannot\n"
"                                   be cleared from here.\n"
"                                   SAFE-RMMOD RULE: when ./resources/\n"
"                                   contains only the mount-* file(s) for the\n"
"                                   mount(s) you are reading through, it is\n"
"                                   safe to `umount` diagfs and then\n"
"                                   `rmmod lkm4ctr`.\n"
"\n"
"The ./v/ subtree (vendor_kernel)\n"
"--------------------------------\n"
"vendor_kernel is exposed as a procfs-style live-resource tree under ./v/:\n"
"  ./v/control                     (0644) read: command help. write: load /\n"
"                                   unload (aliases: remove, graceful) /\n"
"                                   forceunload (aliases: force,\n"
"                                   force_unload). force2 is a module-wide\n"
"                                   escalation on ./status only.\n"
"  ./v/status                      (0444) vendor_kernel's own lifecycle state.\n"
"  ./v/enabled                     (0644) read: \"1\"/\"0\" (the\n"
"                                   vendor_kernel_enabled flag). write:\n"
"                                   \"1\"/\"on\" loads, \"0\"/\"off\" unloads\n"
"                                   vendor_kernel -- a meaningful debug toggle\n"
"                                   of that flag/subsystem.\n"
"  ./v/hooks                       (0444) vendor_kernel's installed hooks.\n"
"  ./v/log                         (0444) vendor_kernel's own log lines.\n"
"  ./v/references                  (0444) vendor_kernel's contribution to\n"
"                                   module_refcount(), broken down.\n"
"  ./v/namespaces                  (0444) full registry dump (every tracked\n"
"                                   tgid->nsproxy) + overlay diag.\n"
"  ./v/resources                   (0444) aggregate live-resource dump.\n"
"  ./v/ns/<type>/                  one directory per namespace type (pid,\n"
"                                   uts, ipc, user, net, time, mnt, cgroup).\n"
"                                   Each lists one file per live instance\n"
"                                   vendor_kernel tracks, named by the owning\n"
"                                   tgid. `cat` shows detail; deleting one\n"
"                                   (rm) SIGKILLs that thread group and frees\n"
"                                   its whole vendored nsproxy (which is\n"
"                                   shared across every ns type for that\n"
"                                   tgid).\n"
"  ./v/ipc/shm|msg|sem/            one directory per SysV IPC class. Each\n"
"                                   lists one file per live object in the\n"
"                                   default vendored ipc namespace, named by\n"
"                                   ipc id; deleting one performs IPC_RMID\n"
"                                   (wakes any blocked waiter with -EIDRM,\n"
"                                   then frees the object).\n"
"  ./v/ipc/mqueue/messages         (0444) POSIX mqueue listing (aggregate;\n"
"                                   per-object mqueue delete is not wired).\n"
"  ./v/hotreload/status            (0444) \"first load\" vs \"hot-reloaded\"\n"
"                                   boot kind, plus in-progress hot-reload\n"
"                                   state.\n"
"  ./v/hotreload/log               (0444) hot-reload subsystem's own log.\n"
"  ./v/hotreload/do-hot-reload     (0200, write-only) write an absolute path\n"
"                                   to a replacement lkm4ctr.ko to trigger a\n"
"                                   hot reload: validate path -> quiesce\n"
"                                   hooks -> drain refcount -> unmount diagfs\n"
"                                   -> hand off to a detached \"rmmod &&\n"
"                                   insmod <path> hotreload=1\" shell -> exit.\n"
"                                   Watch ./v/hotreload/status and\n"
"                                   ./v/hotreload/log for progress.\n"
"\n"
"Notes on design\n"
"---------------\n"
"* On ./status the read side is a strict lifecycle-state readout and the\n"
"  write side is the command surface; ./v/control keeps that same split\n"
"  per-subsystem.\n"
"* This is a small, mostly in-memory pseudo-filesystem in the same spirit\n"
"  as ramfs/securityfs. The fixed skeleton (./status, ./v/* control/status/\n"
"  listing files, and the always-present per-type directories ./resources/,\n"
"  ./v/ns/<type>/, ./v/ipc/<class>/) is built once at mount time; file\n"
"  contents are regenerated fresh on every open(), so state is always live.\n"
"* What IS dynamic are the *leaf* per-instance entries under those per-type\n"
"  directories: the live reference holders under ./resources/, the live\n"
"  vendored namespaces under ./v/ns/<type>/, and the live SysV IPC objects\n"
"  under ./v/ipc/<class>/ appear and disappear on demand (via .lookup/\n"
"  .readdir) as the underlying kernel objects come and go, and each such\n"
"  leaf can be deleted (rm) to tear its underlying resource down.\n"
"* Objects that cannot be enumerated per-instance (currently queued mqueue\n"
"  messages) are exposed as a readable listing file\n"
"  (./v/ipc/mqueue/messages) rather than one dentry per object.\n"
"\n"
"Shell helper (helper.sh)\n"
"------------------------\n"
"helper.sh is meant to be sourced, not executed:\n"
"  export lkm4ctr_diagfs=/path/to/mountpoint\n"
"  . \"$lkm4ctr_diagfs/helper.sh\"\n"
"\n"
"It then defines an `lkm4ctr` dispatcher function and matching standalone\n"
"functions:\n"
"  lkm4ctr mount                    mount -t lkm4ctr diag \"$lkm4ctr_diagfs\"\n"
"  lkm4ctr umount                   unmount \"$lkm4ctr_diagfs\"\n"
"  lkm4ctr status                   summarise /status + /resources + /v state\n"
"  lkm4ctr on                       echo on > /status\n"
"  lkm4ctr off                      echo off > /status (graceful self-unload)\n"
"  lkm4ctr forceunload              echo forceunload > /status\n"
"  lkm4ctr force2                   echo force2 > /status (aggressive escalation)\n"
"  lkm4ctr control <target> <cmd>   write <cmd> to /status (target status) or /v/control (target v)\n"
"  lkm4ctr load [target]            on, or control <target> load\n"
"  lkm4ctr unload [target]          off, or control <target> unload\n"
"  lkm4ctr logcat [target]          cat /log (default), /v/log (\"v\"), or /v/hotreload/log (\"hotreload\")\n"
"  lkm4ctr references               cat /v/references\n"
"  lkm4ctr resources [name [rm]]    list / cat / delete rmmod-blocking holders under /resources\n"
"  lkm4ctr v [subpath]              list the /v live-resource tree, or cat a path under it\n"
"  lkm4ctr hot-upgrade <path-to-ko> echo <path> > /v/hotreload/do-hot-reload\n"
"  lkm4ctr help                     print this command summary\n"
"\n"
"<target> for control is one of: status (module-wide, default) or v.\n"
"$lkm4ctr_diagfs must be exported to the mountpoint before calling any of\n"
"these; every function checks for it and prints a clear error otherwise.\n"
"Run `sh helper.sh` directly (with no arguments) and it just prints this\n"
"same command summary and exits -- it is harmless, but sourcing it is the\n"
"intended usage.\n";

const unsigned long lkm4ctr_readme_txt_size = sizeof(lkm4ctr_readme_txt_data) - 1;
